/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 测试/运维用：清空进程内缓存。 */
export declare function clearRefineCache(): void

/** 探测器独立调用：返回疑点列表（kind/itemId/evidence/hasOp），不打 LLM。 */
export declare function detectSuspects(items: any): any

export const MODEL_ID: string

export const PROMPT_VERSION: string

/**
 * MinerU content_list 清洗。fail-open：任何异常原样返回输入（report.failOpen=true）。
 * 返回 { items, provenance, report }，schema 与 TS/HTTP 版完全一致。
 */
export declare function refine(items: any, opts?: RefineOpts | undefined | null): Promise<any>

export const REFINE_LOGIC_VERSION: string

export interface RefineOpts {
  /** 源文件 SHA256；提供时启用进程内缓存 */
  sha256?: string
  /** 外层循环硬上限；不传则自适应（随疑点数 48~512） */
  maxIterations?: number
  /** 疑点并行裁决数，默认 8；1 = 严格串行 */
  concurrency?: number
  /** MinerU 产物目录绝对路径；提供则 split_table 启用 Qwen-VL 视觉裁决 */
  imageDir?: string
}

/** items → full.md 文本（确定性重渲染，与 MinerU pipeline 拼接规则对齐）。 */
export declare function renderMarkdown(items: any): string
