/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 测试/运维用：清空进程内缓存。 */
export declare function clearRefineCache(): void

export const CONFUSION_PROMPT_VERSION: string

/** 探测器独立调用：返回疑点列表（kind/itemId/evidence/hasOp），不打 LLM。 */
export declare function detectSuspects(items: any): any

export const GARBLED_PROMPT_VERSION: string

export const MODEL_ID: string

export const PROMPT_VERSION: string

/**
 * MinerU content_list 清洗。fail-open：任何异常原样返回输入（report.failOpen=true）。
 * 返回 { items, provenance, report }，schema 与 TS/HTTP 版完全一致。
 *
 * onProgress 可选：清洗阶段每轮迭代回调一次，参数 { iterations, maxIterations,
 * worklistRemaining, inputSuspects }。回调在原生线程上以 NonBlocking 模式投递，
 * 不阻塞清洗；不传则零开销、行为与原先一致。
 */
export declare function refine(items: any, opts?: RefineOpts | undefined | null, onProgress?: ((value: any) => void) | undefined | null): Promise<any>

export const REFINE_LOGIC_VERSION: string

export interface RefineOpts {
  /** 源文件 SHA256；提供时启用进程内缓存 */
  sha256?: string
  /** 外层循环硬上限；不传则自适应（随疑点数 48~512） */
  maxIterations?: number
  /** 疑点并行裁决数，默认 8；1 = 严格串行 */
  concurrency?: number
  /** MinerU 产物目录绝对路径；提供则 split_table 启用 Qwen-VL 视觉裁决 */
  imageDir?: string
  /**
   * OCR 字符混淆修正层（opt-in，默认关）。开启后输出契约变为：
   * 核心层只删不增 + 混淆层在准入名单内做稀疏一换一替换（全量进 report.confusionFixes）
   */
  fixOcrConfusion?: boolean
  /** 混淆准入名单补充对：每项恰好 2 个不同字符（如 "0D" 表示 0↔D 互换可直接落地） */
  extraConfusionPairs?: Array<string>
  /**
   * 重度乱码表的视觉重转写层（opt-in，默认关）。机械检测（词典覆盖率塌方）选定目标，
   * Qwen-VL 对照 img_path 截图逐单元格重转写（全量进 report.tableRewrites，可程序化撤销）。
   * 开启时必须提供 imageDir。
   */
  rewriteGarbledTables?: boolean
  /**
   * 乱码表降级兜底（opt-in，默认关；纯机械，不依赖 LLM/VL）。跑在重转写层之后：
   * 仍判废且有 img_path 的表整项降级为 image（table_body 删除并进 removedSpans，
   * report.tableDegraded 计数）。两层都开 = 先救、救不回再降。
   */
  degradeGarbledTables?: boolean
}

/** items → full.md 文本（确定性重渲染，与 MinerU pipeline 拼接规则对齐）。 */
export declare function renderMarkdown(items: any): string
